# Site settings
title: Homepage of Zhiyuan Zha (查志远)
email: zhazhiyuan.mmd@gmail.com, zhiyuan.zha@ntu.edu.sg.
description: Zhiyuan Zha
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: zhazhiyuan
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
# viewsourceroot: https://github.com/YuBangZheng/yubangzheng.github.io/blob/master/
# this is the url root of the create page link on the footer page.
# newsourceroot: https://github.com/YuBangZheng/yubangzheng.github.io/
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false

port: 4001
